FROM node:22-slim

WORKDIR /workspace/db

RUN npm install -g pnpm

# monorepo root
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /workspace/
# monorepo database
COPY db/package.json db/addTestData.ts /workspace/db/

RUN pnpm install

CMD ["pnpm", "drizzle-kit"]
