FROM node:22-slim

WORKDIR /workspace/nextjs

RUN npm install -g pnpm

# monorepo root
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /workspace/
# monorepo db
COPY db/package.json /workspace/db/
# monorepo server-hono
COPY server-hono/package.json /workspace/server-hono/
# monorepo nextjs
COPY nextjs/package.json nextjs/tsconfig.json /workspace/nextjs/

RUN pnpm install

CMD ["pnpm", "dev"]

